name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "xugou_db"
database_id = "cf619fcd-81e2-4554-94b4-7123d12e0dc1"

[version_metadata]
binding = "CF_VERSION_METADATA"
